# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/alfonso/TFM/ewic-fpga_v2/ewic-fpga/uart_design.srcs/sources_1/ip/uart_fifo_1/uart_fifo.xci
# IP: The module: 'uart_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alfonso/TFM/ewic-fpga_v2/ewic-fpga/uart_design.gen/sources_1/ip/uart_fifo/uart_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_fifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/alfonso/TFM/ewic-fpga_v2/ewic-fpga/uart_design.gen/sources_1/ip/uart_fifo/uart_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/alfonso/TFM/ewic-fpga_v2/ewic-fpga/uart_design.srcs/sources_1/ip/uart_fifo_1/uart_fifo.xci
# IP: The module: 'uart_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alfonso/TFM/ewic-fpga_v2/ewic-fpga/uart_design.gen/sources_1/ip/uart_fifo/uart_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/alfonso/TFM/ewic-fpga_v2/ewic-fpga/uart_design.gen/sources_1/ip/uart_fifo/uart_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
